export const TABLE_HEAD = [
  "Organisation ID",
  "Organisation Name",
  "Type",
  "Registration Date",
  "Email",
  "Availability",
];

export const TABLE_ROWS = [
  {
    organisationID: "ORG123",
    organisationName: "ABC Corp",
    type: "Corporation",
    registrationDate: "2023-01-15",
    email: "abc@corp.com",
    availability: "Active",
  },
  {
    organisationID: "ORG124",
    organisationName: "XYZ Ltd",
    type: "Limited",
    registrationDate: "2022-05-20",
    email: "xyz@ltd.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG125",
    organisationName: "PQR Inc",
    type: "Incorporated",
    registrationDate: "2021-11-10",
    email: "pqr@inc.com",
    availability: "Active",
  },
  {
    organisationID: "ORG126",
    organisationName: "LMN LLC",
    type: "Limited Liability",
    registrationDate: "2020-08-05",
    email: "lmn@llc.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG127",
    organisationName: "DEF Enterprises",
    type: "Enterprise",
    registrationDate: "2019-03-25",
    email: "def@ent.com",
    availability: "Active",
  },
  {
    organisationID: "ORG128",
    organisationName: "GHI Group",
    type: "Group",
    registrationDate: "2018-09-10",
    email: "ghi@group.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG129",
    organisationName: "JKL Corporation",
    type: "Corporation",
    registrationDate: "2017-06-15",
    email: "jkl@corp.com",
    availability: "Active",
  },
  {
    organisationID: "ORG130",
    organisationName: "MNO Ltd",
    type: "Limited",
    registrationDate: "2016-02-20",
    email: "mno@ltd.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG131",
    organisationName: "PST Inc",
    type: "Incorporated",
    registrationDate: "2015-10-30",
    email: "pst@inc.com",
    availability: "Active",
  },
  {
    organisationID: "ORG132",
    organisationName: "QRS LLC",
    type: "Limited Liability",
    registrationDate: "2014-11-25",
    email: "qrs@llc.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG133",
    organisationName: "TUV Enterprises",
    type: "Enterprise",
    registrationDate: "2013-04-20",
    email: "tuv@ent.com",
    availability: "Active",
  },
  {
    organisationID: "ORG134",
    organisationName: "WXY Group",
    type: "Group",
    registrationDate: "2012-08-10",
    email: "wxy@group.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG135",
    organisationName: "ABC Corp 2",
    type: "Corporation",
    registrationDate: "2011-05-15",
    email: "abc2@corp.com",
    availability: "Active",
  },
  {
    organisationID: "ORG136",
    organisationName: "XYZ Ltd 2",
    type: "Limited",
    registrationDate: "2010-03-20",
    email: "xyz2@ltd.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG137",
    organisationName: "PQR Inc 2",
    type: "Incorporated",
    registrationDate: "2009-11-10",
    email: "pqr2@inc.com",
    availability: "Active",
  },
  {
    organisationID: "ORG138",
    organisationName: "LMN LLC 2",
    type: "Limited Liability",
    registrationDate: "2008-07-05",
    email: "lmn2@llc.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG139",
    organisationName: "DEF Enterprises 2",
    type: "Enterprise",
    registrationDate: "2007-02-25",
    email: "def2@ent.com",
    availability: "Active",
  },
  {
    organisationID: "ORG140",
    organisationName: "GHI Group 2",
    type: "Group",
    registrationDate: "2006-08-10",
    email: "ghi2@group.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG141",
    organisationName: "JKL Corporation 2",
    type: "Corporation",
    registrationDate: "2005-04-15",
    email: "jkl2@corp.com",
    availability: "Active",
  },
  {
    organisationID: "ORG142",
    organisationName: "MNO Ltd 2",
    type: "Limited",
    registrationDate: "2004-12-20",
    email: "mno2@ltd.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG143",
    organisationName: "PST Inc 2",
    type: "Incorporated",
    registrationDate: "2003-10-30",
    email: "pst2@inc.com",
    availability: "Active",
  },
  {
    organisationID: "ORG144",
    organisationName: "QRS LLC 2",
    type: "Limited Liability",
    registrationDate: "2002-09-25",
    email: "qrs2@llc.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG145",
    organisationName: "TUV Enterprises 2",
    type: "Enterprise",
    registrationDate: "2001-05-20",
    email: "tuv2@ent.com",
    availability: "Active",
  },
  {
    organisationID: "ORG146",
    organisationName: "WXY Group 2",
    type: "Group",
    registrationDate: "2000-11-10",
    email: "wxy2@group.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG147",
    organisationName: "ABC Corp 3",
    type: "Corporation",
    registrationDate: "1999-09-15",
    email: "abc3@corp.com",
    availability: "Active",
  },
  {
    organisationID: "ORG148",
    organisationName: "XYZ Ltd 3",
    type: "Limited",
    registrationDate: "1998-07-20",
    email: "xyz3@ltd.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG149",
    organisationName: "PQR Inc 3",
    type: "Incorporated",
    registrationDate: "1997-04-10",
    email: "pqr3@inc.com",
    availability: "Active",
  },
  {
    organisationID: "ORG150",
    organisationName: "LMN LLC 3",
    type: "Limited Liability",
    registrationDate: "1996-02-05",
    email: "lmn3@llc.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG151",
    organisationName: "DEF Enterprises 3",
    type: "Enterprise",
    registrationDate: "1995-01-25",
    email: "def3@ent.com",
    availability: "Active",
  },
  {
    organisationID: "ORG152",
    organisationName: "GHI Group 3",
    type: "Group",
    registrationDate: "1994-06-10",
    email: "ghi3@group.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG153",
    organisationName: "JKL Corporation 3",
    type: "Corporation",
    registrationDate: "1993-03-15",
    email: "jkl3@corp.com",
    availability: "Active",
  },
  {
    organisationID: "ORG154",
    organisationName: "MNO Ltd 3",
    type: "Limited",
    registrationDate: "1992-12-20",
    email: "mno3@ltd.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG155",
    organisationName: "PST Inc 3",
    type: "Incorporated",
    registrationDate: "1991-10-30",
    email: "pst3@inc.com",
    availability: "Active",
  },
  {
    organisationID: "ORG156",
    organisationName: "QRS LLC 3",
    type: "Limited Liability",
    registrationDate: "1990-09-25",
    email: "qrs3@llc.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG157",
    organisationName: "TUV Enterprises 3",
    type: "Enterprise",
    registrationDate: "1989-04-20",
    email: "tuv3@ent.com",
    availability: "Active",
  },
  {
    organisationID: "ORG158",
    organisationName: "WXY Group 3",
    type: "Group",
    registrationDate: "1988-08-10",
    email: "wxy3@group.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG159",
    organisationName: "ABC Corp 4",
    type: "Corporation",
    registrationDate: "1987-05-15",
    email: "abc4@corp.com",
    availability: "Active",
  },
  {
    organisationID: "ORG160",
    organisationName: "XYZ Ltd 4",
    type: "Limited",
    registrationDate: "1986-03-20",
    email: "xyz4@ltd.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG161",
    organisationName: "PQR Inc 4",
    type: "Incorporated",
    registrationDate: "1985-11-10",
    email: "pqr4@inc.com",
    availability: "Active",
  },
  {
    organisationID: "ORG162",
    organisationName: "LMN LLC 4",
    type: "Limited Liability",
    registrationDate: "1984-07-05",
    email: "lmn4@llc.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG163",
    organisationName: "DEF Enterprises 4",
    type: "Enterprise",
    registrationDate: "1983-02-25",
    email: "def4@ent.com",
    availability: "Active",
  },
  {
    organisationID: "ORG164",
    organisationName: "GHI Group 4",
    type: "Group",
    registrationDate: "1982-06-10",
    email: "ghi4@group.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG165",
    organisationName: "JKL Corporation 4",
    type: "Corporation",
    registrationDate: "1981-04-15",
    email: "jkl4@corp.com",
    availability: "Active",
  },
  {
    organisationID: "ORG166",
    organisationName: "MNO Ltd 4",
    type: "Limited",
    registrationDate: "1980-12-20",
    email: "mno4@ltd.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG167",
    organisationName: "PST Inc 4",
    type: "Incorporated",
    registrationDate: "1979-10-30",
    email: "pst4@inc.com",
    availability: "Active",
  },
  {
    organisationID: "ORG168",
    organisationName: "QRS LLC 4",
    type: "Limited Liability",
    registrationDate: "1978-09-25",
    email: "qrs4@llc.com",
    availability: "Inactive",
  },
  {
    organisationID: "ORG169",
    organisationName: "TUV Enterprises 4",
    type: "Enterprise",
    registrationDate: "1977-05-20",
    email: "tuv4@ent.com",
    availability: "Active",
  },
  {
    organisationID: "ORG170",
    organisationName: "WXY Group 4",
    type: "Group",
    registrationDate: "1976-11-10",
    email: "wxy4@group.com",
    availability: "Inactive",
  },
];
